controller_list:
  - name: test1_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    default: true
    joints: [left_rotary1, left_link1, left_link2, left_rotary2, left_effector, right_rotary1, right_link1, right_link2, right_rotary2, right_effector]
